### ISSUE TITLE
Always return null when get data from tokyo tyrant

### ISSUE THREAD

**Issue by yheart** [gwhalin/Memcached-Java-Client#8] opened 2010-06-04 06:10 UTC
Hi,when I try to get data from tokyo tyrant by java memcached,it allways return null,but correct when by spymemcached,so should I implement my own decoder for tokyo tyrant ? or is there any exsited solution for java memcached ? thank you very much~~

**Comment by newroot** [comment] 2010-06-07 08:11
which version are you using? 2.5.1 or 2.0.1?
I will try to reproduce this issue with the version 2.5.1 together with latest tykyo tyrant as soon as possible.

**Comment by yheart** [comment] 2010-06-08 15:39
Hi,I'm using 2.5.1 , thank you for your response :)

**Comment by happybyron** [comment] 2010-06-12 02:05
Hi yheart:
I have reproduced the problem with 2.5.1 as well. However, during the debug, I have found the flag number returned by ttserver always is 0 which not implemented as same as Memcached server. you can find more about the memcached protocol here: http://code.sixapart.com/svn/memcached/trunk/server/doc/protocol.txt
Therefore, base on the return flag number, our client is not able to retrieve the value. That is what we found so far and we will try to figure out a way to get around with it in the future.

Thanks a lot for letting us know about the problem.

**Comment by happybyron** [comment] 2010-06-18 06:49
Hello yheart:
During the research, I have found since our memcached client distinguishes different object type and set different different flag value to improve the performance, SpyMemcached stores all values as object only which will reduce the performance. In source code, if you change the code in class AscIIClient.java line 373, int flag = 0, using our client to set value and get value, it will works very well. However, the performance will be lower than b4.

**Comment by newroot** [comment] 2010-06-23 01:58
Because tykyo tyrant doesn't support flag as stock memcached, we will close this issue.

**Closed as completed by newroot** 2010-06-23 01:58 UTC
