### ISSUE TITLE
NullPointerException  of memcached-client2.5.1 in Jmeter testing

### ISSUE THREAD

**Issue by weiqinyang** [gwhalin/Memcached-Java-Client#12] opened 2010-06-11 07:29 UTC
Test tools:jakarta-jmeter-2.3.2
Thread number: 100,500,1000
Error:
java.lang.NullPointerException
        at com.schooner.MemCached.SchoonerSockIOPool.getConnection(SchoonerSockIOPool.java:590)
        at com.schooner.MemCached.SchoonerSockIOPool.getSock(SchoonerSockIOPool.java:514)
        at com.schooner.MemCached.AscIIClient.set(AscIIClient.java:376)
        at com.schooner.MemCached.AscIIClient.set(AscIIClient.java:241)
        at com.danga.MemCached.MemCachedClient.set(MemCachedClient.java:603)
        at test.TestMemcachedSet.setkey(TestMemcachedSet.java:126)
        at test.TestMemcachedSet.runTest(TestMemcachedSet.java:101)
        at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:161)
        at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:290)
        at java.lang.Thread.run(Unknown Source)

TestCode:

public class TestMemcachedSet extends AbstractJavaSamplerClient {
    private SampleResult results;
    private String key;
    private String value;
    static SockIOPool pool;
    static MemCachedClient mc;
    private String serverlist;
    private static int timeout;

```
public void setupTest(JavaSamplerContext arg0) {        

    results = new SampleResult();
    timeout = arg0.getIntParameter("timeout");
    key = arg0.getParameter("key");
    value = arg0.getParameter("value");
    serverlist = arg0.getParameter("serverlist");

    if (key != null && key.length() > 0) {
        results.setSamplerData(key);

    }   
    if (value != null && value.length() > 0) {
        results.setSamplerData(value);

    }
    if (serverlist != null && serverlist.length() > 0) {
        results.setSamplerData(serverlist);

    }   
}



public Arguments getDefaultParameters() {
    Arguments params = new Arguments();

    params.addArgument("serverlist", "172.20.57.167:11211,172.20.57.112:11211");
    params.addArgument("timeout", "5000"); 
    params.addArgument("key", "key"); 
    params.addArgument("value", "value");                                   

    return params;
}



public SampleResult runTest(JavaSamplerContext arg0) {

    results.sampleStart();  

    boolean result=false;

    try{
      results.setRequestHeaders(key);
      result = setkey(key,value);   
      results.setResponseMessage("set data:"+key+" is "+result);
      results.setSuccessful(result);
    }catch(Exception e){
        e.printStackTrace();
        results.setSuccessful(result);
    }finally {
        // Record end time and populate the results.
      results.sampleEnd();

    }

    return results;
}

public void teardownTest(JavaSamplerContext arg0) {
    //nothing todo  
}

private boolean setkey(String key,String value)
{
    pool = SockIOPool.getInstance();
    pool.setServers(serverlist.split(","));
    Integer[] weights={1,2};
    pool.setWeights(weights);

    pool.setNagle( false );
    pool.setSocketTO(timeout );

    pool.setHashingAlg(2);

    pool.initialize();
    mc = new MemCachedClient();

    mc.setPrimitiveAsString(true); 
    mc.setSanitizeKeys(false);
    boolean result = mc.set(key, value);
    pool.shutDown();
    return result ;
}
```

}

**Comment by happybyron** [comment] 2010-06-23 02:24
thanks a lot for reporting the issues. could you list step by step how did you produce the problem?

**Comment by weiqinyang** [comment] 2010-06-23 02:58
Thanks happybyron.
My test steps is like this:
1)copy  TestMemcachedSet.jar and memcached-client2.5.1.jar to JMeter_home/lib/ext/ ;
2)Create a JAVA Request JMeter Sampler,select TestMemcachedSet to run .
Jmeter's manual :http://jakarta.apache.org/jmeter/usermanual/component_reference.html#Java_Request
 But,when I used memcached-client 2.0.1, it runs well.

**Comment by xuhuleon** [comment] 2010-06-23 03:22
hi weiqian, I've done same thing as you said. But how can I get the result? There is no response when I click run->start

**Comment by weiqinyang** [comment] 2010-06-23 03:42
You can new some listeners under Test Plan for Graph Results, for example: Aggregate Report,View Results Tree.
The manual url: http://jakarta.apache.org/jmeter/usermanual/component_reference.html#Graph_Results

**Comment by happybyron** [comment] 2010-06-23 05:58
Hi Yang:
try to copy all the resources jar file in memcached client and your project into %JMETER_HOME%/lib and then give a try.

**Comment by weiqinyang** [comment] 2010-06-24 01:57
hi happybyron:
I have tried it,but the same NullPointerException occurred when more than 100 threads  runing every 1 second.And there was a new error like below when more than 100 threads :
com.schooner.MemCached.SchoonerSockIOPool Thu Jun 24 09:37:34 CST 2010 - ++++ fa
iled to get SockIO obj for: 172.20.67.105:11211

Any ideas can help me solve the problem ?

**Comment by xuhuleon** [comment] 2010-06-24 02:08
I think this error is caused by TIME_WAIT status  during TCP connection closing. 
Run "netstat -an|grep 11211" on your server to check if I'm right.
If I'm right, try sudo sysctl -w net.ipv4.tcp_tw_recycle=1.

**Comment by xuhuleon** [comment] 2010-06-24 08:19
I found the error is caused by your code not memcached client. The initialize() and shutdown() of pool should not be called in each thread. They should only be called once. The java.lang.NullPointerException happens when some thread try get connection from pool after another thread has shutdown the pool.
BTW: SampleResult results should not be shared with all threads, please see jmeter.log for the error info.

Please refer my code for more info:

package com.schooner.MemCached;

import java.util.concurrent.atomic.AtomicInteger;

import org.apache.jmeter.config.Arguments;
import org.apache.jmeter.protocol.java.sampler.AbstractJavaSamplerClient;
import org.apache.jmeter.protocol.java.sampler.JavaSamplerContext;
import org.apache.jmeter.samplers.SampleResult;
import com.danga.MemCached.MemCachedClient;
import com.danga.MemCached.SockIOPool;

public class JmetTest extends AbstractJavaSamplerClient{

```
private String key;
private String value;
private static SockIOPool pool = null;
private static AtomicInteger flag = new AtomicInteger();
static MemCachedClient mc;
private String serverlist;
private static int timeout;

public void setupTest(JavaSamplerContext arg0) {        


    timeout = arg0.getIntParameter("timeout");
    key = arg0.getParameter("key");
    value = arg0.getParameter("value");
    serverlist = arg0.getParameter("serverlist");

    if(flag.get() == 0) {
        init();
    }
}

synchronized private void init(){
    System.out.println(serverlist + " "  + key + " " + value);
    pool = SockIOPool.getInstance();
    pool.setServers(serverlist.split(","));
```

//      Integer[] weights={1,2};
//      pool.setWeights(weights);

//      pool.setNagle( false );
        pool.setSocketTO(timeout );

//      pool.setHashingAlg(2);

```
    pool.setMaxConn(100);
    pool.initialize();
    mc = new MemCachedClient();
```

//      mc.setPrimitiveAsString(true); 
//      mc.setSanitizeKeys(false);
        flag.set(1);

```
}

public Arguments getDefaultParameters() {
    Arguments params = new Arguments();

    params.addArgument("serverlist", "172.16.11.40:11211");
    params.addArgument("timeout", "5000"); 
    params.addArgument("key", "key"); 
    params.addArgument("value", "value");                                   

    return params;
}



public SampleResult runTest(JavaSamplerContext arg0) {
    SampleResult results = new SampleResult();
    results.setSampleLabel("memcached" );
    boolean result=false;

    try{
      results.sampleStart();  
      result = mc.set(key,value);   
      results.setSuccessful(result);
    }catch(Exception e){
        e.printStackTrace();
        results.setSuccessful(result);
    }finally {
        // Record end time and populate the results.
      results.sampleEnd();

    }
    return results;
}

public void teardownTest(JavaSamplerContext arg0) {
}
```

}

**Comment by xuhuleon** [comment] 2010-06-24 08:22
I can't find any function to write pool.shutdown() ... I think jmeter is not suitable to test app with connection pools.. If you want use it, you'd better modify its source code.

**Comment by weiqinyang** [comment] 2010-06-24 08:45
Thanks very much for xuhuleon's reply.
May Be your are right, I will try other method to test .
But I have another question, if it cansed by Jmeter tool, why  java-memcached-2.0.1client can run well when more then 100 theads.

**Comment by xuhuleon** [comment] 2010-06-25 03:12
I have tried your code in 2.0.1, but the same error happened...

**Comment by weiqinyang** [comment] 2010-06-25 03:21
Thanks very much. I will try other ways for memcached's concurrent test .

**Comment by newroot** [comment] 2010-07-19 03:09
Thanks, Weiqin.

**Closed as completed by newroot** 2010-07-19 03:09 UTC
